import { supabase } from './supabase';

const getDefaultSections = () => [
    {
      id: "hero",
      type: "hero",
      title: "Hero Section",
      visible: true,
      sort_order: 1,
      content: {
        heading: "PRECISION PERFORMANCE PERFECTION",
        subheading: "Where automotive excellence meets cutting-edge service",
        description: "Experience the pinnacle of automotive luxury and performance",
        buttonText: "BROWSE CARS",
        buttonLink: "/inventory",
        backgroundColor: "#0B0B0C",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
    {
      id: "services",
      type: "services",
      title: "Services Section",
      visible: true,
      sort_order: 2,
      content: {
        heading: "PRECISION SERVICE",
        description: "Expert automotive service with state-of-the-art equipment and certified technicians",
        backgroundColor: "#0B0B0C",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
    {
      id: "inventory",
      type: "inventory",
      title: "Inventory Section",
      visible: true,
      sort_order: 3,
      content: {
        heading: "NEW ARRIVALS",
        description: "Latest additions to our premium collection",
        backgroundColor: "#141518",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
    {
      id: "trust",
      type: "trust",
      title: "Trust Section",
      visible: true,
      sort_order: 4,
      content: {
        heading: "TRUSTED BY THOUSANDS",
        description: "Join thousands of satisfied customers who trust us with their automotive needs",
        backgroundColor: "#0B0B0C",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
    {
      id: "finance",
      type: "finance",
      title: "Finance Section",
      visible: true,
      sort_order: 5,
      content: {
        heading: "FINANCE OPTIONS",
        description: "Get pre-qualified in minutes with competitive CAD rates and flexible terms",
        backgroundColor: "#1A1B1E",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
    {
      id: "promo",
      type: "promo",
      title: "Promo Section",
      visible: true,
      sort_order: 6,
      content: {
        heading: "PERFORMANCE SERVICE SPECIAL",
        description: "Complete performance package including diagnostics, tune-up, and optimization",
        backgroundColor: "#0B0B0C",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
    {
      id: "map",
      type: "map",
      title: "Map Section",
      visible: true,
      sort_order: 7,
      content: {
        heading: "VISIT US",
        description: "Experience our state-of-the-art facility and meet our expert team",
        backgroundColor: "#1A1B1E",
        textColor: "#FFFFFF",
        accentColor: "#D7FF00",
      },
    },
];

export const seedDatabase = async () => {
    if (!supabase) {
        return { success: false, error: "Supabase client not available." };
    }

    try {
        console.log("🌱 Starting database seed process...");

        // 1. Check if content already exists
        const { data: existingData, error: checkError } = await supabase
            .from('content_sections')
            .select('id')
            .limit(1);

        if (checkError) {
            throw checkError;
        }

        if (existingData && existingData.length > 0) {
            console.log("✅ Database already seeded. Skipping.");
            return { success: true, message: "Database already contains content." };
        }

        // 2. Prepare data for insertion (map to match DB columns)
        const sectionsToInsert = getDefaultSections().map(section => ({
            // id is auto-generated by DB, so we omit it.
            section_type: section.type,
            title: section.title,
            visible: section.visible,
            sort_order: section.sort_order,
            content: section.content,
        }));

        console.log(`🌱 Inserting ${sectionsToInsert.length} sections...`);

        // 3. Insert the data
        const { error: insertError } = await supabase
            .from('content_sections')
            .insert(sectionsToInsert);

        if (insertError) {
            throw insertError;
        }

        console.log("✅ Database seeded successfully!");
        return { success: true, message: "Database seeded successfully!" };

    } catch (error: any) {
        console.error("❌ Error during database seeding:", error);
        return { success: false, error: error.message || "An unknown error occurred." };
    }
};
